from __future__ import annotations

from pathlib import Path

BASE_URL = "https://ygoprodeck.com"
DEFAULT_DATABASE_PATH = Path("data/ygo.sqlite")
DEFAULT_META_DECK_CATEGORY_URL = f"{BASE_URL}/category/format/tournament%20meta%20decks"
DEFAULT_META_DECK_API_URL = f"{BASE_URL}/api/decks/getDecks.php"
DEFAULT_META_DECK_API_FORMAT = "tournament%20meta%20decks"
DEFAULT_CATEGORY_PAGE_SIZE = 20
DEFAULT_INITIAL_CRAWL_PAGE_COUNT = 100
DEFAULT_TIMEOUT_SECONDS = 30.0
DEFAULT_USER_AGENT = "ygo-crawler/0.1 (+local-dev)"
CARD_INFO_API_URL = "https://db.ygoprodeck.com/api/v7/cardinfo.php"
CARD_METADATA_BATCH_SIZE = 40
CARD_METADATA_VERSION = 4

NON_ENGINE_MIN_TOTAL_DECKS = 20
NON_ENGINE_MIN_DECK_GROUPS = 8
NON_ENGINE_MIN_GROUP_SPREAD_RATIO = 0.04
NON_ENGINE_MAX_GROUP_SHARE = 0.35
NON_ENGINE_MAX_ARCHETYPE_MATCH_SHARE = 0.45

NON_ENGINE_SPLASH_MIN_TOTAL_DECKS = 8
NON_ENGINE_SPLASH_MIN_DECK_GROUPS = 2
NON_ENGINE_SPLASH_MAX_GROUP_SHARE = 0.8

EXCLUDED_MARKERS = ("ocg", "genyssis", "genesis")
TCG_MARKER = "tcg"